export const messages = [
    { id: 1, message: "What's the most inspiring thing you've ever read?" },
    { id: 2, message: "If you could be any age for a week, what age would you choose?" },
    { id: 3, message: "What's the most spontaneous thing you've ever done?" },
    { id: 4, message: "If you could change your first name, what would you pick?" },
    { id: 5, message: "What's a song that always lifts your mood?" },
    { id: 6, message: "If you could visit any planet, which one would it be?" },
    { id: 7, message: "What's a talent you wish you had?" },
    { id: 8, message: "What's your favorite way to spend a weekend?" },
    { id: 9, message: "If you could have a superpower, what would it be?" },
    { id: 10, message: "What's the best advice you've ever received?" },
    { id: 11, message: "If you could relive any moment in your life, what would it be?" },
    { id: 12, message: "What's the most beautiful place you've ever seen?" },
    { id: 13, message: "If you could have any job in the world, what would it be?" },
    { id: 14, message: "What's a movie you could watch over and over again?" },
    { id: 15, message: "If you could be fluent in any language, which would it be?" },
    { id: 16, message: "What's the most memorable meal you've ever had?" },
    { id: 17, message: "If you could design your dream home, what would it look like?" },
    { id: 18, message: "What's a book you think everyone should read?" },
    { id: 19, message: "If you could live in any country, where would you go?" },
    { id: 20, message: "What's a piece of technology you wish existed?" },
    { id: 21, message: "What's the most unusual food you've ever tried?" },
    { id: 22, message: "If you could spend a day with any celebrity, who would it be?" },
    { id: 23, message: "What's a goal you've recently achieved?" },
    { id: 24, message: "If you could be any fictional character, who would you be?" },
    { id: 25, message: "What's your favorite thing about the place you live?" },
    { id: 26, message: "If you could invent something, what would it be?" },
    { id: 27, message: "What's a piece of art that has influenced you?" },
    { id: 28, message: "If you could only eat one cuisine for the rest of your life, what would it be?" },
    { id: 29, message: "What's a tradition you cherish?" },
    { id: 30, message: "If you could time travel to the future, what would you want to see?" },
    { id: 31, message: "What's something you're passionate about?" },
    { id: 32, message: "If you could attend any event in history, what would it be?" },
    { id: 33, message: "What's a dream destination on your travel list?" },
    { id: 34, message: "If you could learn any skill instantly, what would it be?" },
    { id: 35, message: "What's a childhood memory that makes you smile?" },
    { id: 36, message: "If you could be an expert in any field, what would it be?" },
    { id: 37, message: "What's a quote that motivates you?" },
    { id: 38, message: "If you could own any rare item, what would it be?" },
    { id: 39, message: "What's the best gift you've ever received?" },
    { id: 40, message: "If you could change one law, what would it be?" },
    { id: 41, message: "What's a place you've always wanted to visit but haven't yet?" },
    { id: 42, message: "If you could meet your younger self, what advice would you give?" },
    { id: 43, message: "What's the most challenging thing you've accomplished?" },
    { id: 44, message: "If you could start a business, what would it be?" },
    { id: 45, message: "What's the most creative thing you've ever done?" },
    { id: 46, message: "If you could solve one world problem, what would it be?" },
    { id: 47, message: "What's a personal project you're working on?" },
    { id: 48, message: "If you could visit any museum in the world, which one would it be?" },
    { id: 49, message: "What's the most adventurous thing you've ever done?" },
    { id: 50, message: "If you could make a documentary about anything, what would it be?" },
  ];

  export const carouselMessages =  [
    { id: 1, title: "Message from mysteryUser", content: "What is your favorite hobby?" },
    { id: 2, title: "Message from secretAdmirer", content: "What inspires you the most?" },
    { id: 3, title: "Message from anonymousFriend", content: "What is your dream vacation spot?" },
    { id: 4, title: "Message from mysteryUser", content: "What is your biggest fear?" },
    { id: 5, title: "Message from unknownSender", content: "What makes you smile?" },
    { id: 6, title: "Message from hiddenStranger", content: "Who is your role model?" },
    { id: 7, title: "Message from mysteryUser", content: "What is your favorite book?" },
    { id: 8, title: "Message from anonymousFriend", content: "What motivates you every day?" },
    { id: 9, title: "Message from secretAdmirer", content: "What is your happiest memory?" },
    { id: 10, title: "Message from unknownSender", content: "What is your favorite movie?" },
    { id: 11, title: "Message from hiddenStranger", content: "What do you value most in life?" },
    { id: 12, title: "Message from mysteryUser", content: "What is your biggest accomplishment?" },
    { id: 13, title: "Message from anonymousFriend", content: "What is your favorite quote?" },
    { id: 14, title: "Message from secretAdmirer", content: "What do you enjoy doing in your free time?" },
    { id: 15, title: "Message from unknownSender", content: "What is your dream job?" }
  ];
  