import { Inter } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import Navbar from "@/components/Navbar";
import "./globals.css"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
        <body className={` ${inter.className} bg-neutral-950 text-white`}>
      <AuthProvider>
          <Navbar />
          {children}
          <Toaster />
      </AuthProvider>
          </body>
    </html>
  );
}
