import { Inter } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import Navbar from "@/components/Navbar";
import "./globals.css"
// import { auth } from "@/auth";
// import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const session = auth()
  return (
    <html lang="en">
        <body className={inter.className}>
      <AuthProvider>
          <Navbar />
          {children}
          <Toaster />
      </AuthProvider>
          </body>
    </html>
  );
}
